---

kind: pipeline
type: docker
name: release

steps:

- name: Build
  image: alpine
  environment:
    TAG: ${DRONE_TAG}
  commands:
  - mkdir build
  - cp -a bin build/
  - cp -a .bonsai.yml build/
  - tar -C build -cvzf sensu-check-lvm-thinpool_$TAG_linux_amd64.tar.gz .
  - sha512sum sensu-check-lvm-thinpool_$TAG_linux_amd64.tar.gz > sensu-check-lvm-thinpool_$TAG_sha512_checksums.txt

- name: Release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: GITHUB_RELEASE_TOKEN
    files:
      - sensu-check-lvm-thinpool_*
    checksum:
      - sha512
trigger:
  event:
    - tag
